name: Robot Framework Automated API Tests

on:
  push:
    paths:
      - 'tests/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ต้องเปิดสิทธิ์เพื่อให้เขียนลง gh-pages ได้

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-requests requests

      - name: Create Custom InfluxDB Listener
        run: |
          cat <<EOF > influx_listener.py
          import requests
          import sys

          class influx_listener:
              ROBOT_LISTENER_API_VERSION = 2

              def __init__(self, url, token, org, bucket, report_url):
                  self.url = f"{url}/api/v2/write?org={org}&bucket={bucket}&precision=s"
                  self.headers = {"Authorization": f"Token {token}", "Content-Type": "text/plain; charset=utf-8"}
                  self.report_url = report_url # รับค่า URL ที่ส่งมาจาก Workflow

              def end_test(self, name, attrs):
                  status = 1 if attrs['status'] == 'PASS' else 0
                  duration = attrs['elapsedtime'] / 1000.0
                  # เพิ่ม reportUrl เข้าไปใน Line Protocol (สังเกตเครื่องหมาย " ครอบ URL)
                  data = f'test_cases,test_name={name.replace(" ", "_")},project=ecommerce status={status},duration={duration},reportUrl="{self.report_url}"'
                  try:
                      requests.post(self.url, headers=self.headers, data=data, timeout=5)
                  except Exception as e:
                      print(f"Failed to send data to InfluxDB: {e}")
          EOF

      - name: Run Robot Framework Tests
        run: |
          mkdir -p results
          # สร้าง URL ล่วงหน้าโดยใช้ github.run_id
          FINAL_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_id }}/log.html"
          
          echo "Test Report will be available at: $FINAL_URL"

          # ส่ง FINAL_URL เข้าไปเป็น argument ตัวสุดท้ายของ listener
          robot -d results \
          --listener "influx_listener.py;https://a0a7-131-229-247-58.ngrok-free.app;-5BwTjLE1hJxif2RJbjuuiBt_W0q1_cWP9CI5AZcp9CwY595hXVHF7O-hA8gpzbO6wW7m54KkIVSdZ2-sy7IyA==;my-org;robot-metrics;$FINAL_URL" \
          tests/**/*.robot

      - name: Deploy Test Results to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results
          destination_dir: ${{ github.run_id }} 
          keep_files: true 

      - name: Upload Artifact (Backup)
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/